### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
Fastlane "starter package". You will soon be asked for this, as F-Droid needs it (for your [RFP](https://gitlab.com/fdroid/rfp/-/issues/1613)). It would be nice if you could also add screenshots to this structure. To guide you, I can provide you with my [Fastlane Cheat-Sheet](https://gitlab.com/snippets/1895688). If you've got questions, we gladly assist.

### CODE REVIEW

**Comment by Mystro256** [comment]
Thanks! I'll pull this in and add some more metadata and translations.

I assume this needs to be in a tagged commit (i.e. like a released version) for fdroid to pick it up?

**Comment by Mystro256** [comment]
Also, shouldn't the german translation be de-DE? Or does fdroid allow for this?

**Comment by IzzySoft** [comment]
> I'll pull this in and add some more metadata and translations.

Great, thanks!

> I assume this needs to be in a tagged commit

Yes.

> Also, shouldn't the german translation be de-DE?

Not necessarily. The only one required in that format by F-Droid is `en-US`. For other languages you only need that on two occasions:

* you want to deploy to Play Store (they require it for all languages)
* you want to distinguish between `de-DE` and `de_AT` (which would be a little overkill here IMHO)

**Comment by Mystro256** [comment]
Thanks! I'll probably switch it to de-DE if I decide to add it to the Play Store, but no need for now.

I've added some metadata. Can you confirm this is sufficient? I skipped the screenshots and whatnot as it's not really useful for this app. I followed up in the fdroid RFP. I'm looking to get this into fdroid, with room to improve it as I go.

**Comment by IzzySoft** [comment]
> I've added some metadata. Can you confirm this is sufficient?

Technicall "sufficient" it was already with this PR ("minimum requirements" fulfilled) – but yes, that's very fine, thanks!

> I skipped the screenshots and whatnot as it's not really useful for this app.

If there is not even a config screen – right, what kind of screenshot should one ship? Play Store requires you to ship at least two. Now check some apps which offer no screens at all and you see what headache that gives to the devs. No: while very nice to have ("a picture speaks louder than words" and all that), it's not mandatory with F-Droid. And everything not available in one language will be picked from `en-US` – like the per-release changelogs for a French user.

> I'm looking to get this into fdroid, with room to improve it as I go.

Absolutely fine, thanks a lot! Feel free to "jump up" to "1.3,4" in `build.gradle`, adding `4.txt` to the changelogs in Fastlane – and then `git tag 1.3 && git push --tags` – and we'll proceed with your RFP :smiley:

**Comment by Mystro256** [comment]
Makes a lot of sense, thanks for all the help! Everything is tagged and ready to go! :)

**Comment by IzzySoft** [comment]
Thanks! Then let's [give it a look](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8177), shall we? :crossed_fingers:

**Pull request merged**
